classdef TestFieldKernel < matlab.unittest.TestCase
%TESTFIELDKERNEL Tests the projected-parameter and implicit-field kernel.

    properties (Access = private)
        BaseDir
        Config
    end

    methods (TestClassSetup)
        function setupClass(testCase)
            testFile = mfilename('fullpath');
            testCase.BaseDir = fileparts(fileparts(testFile));
            addpath(fullfile(testCase.BaseDir, 'core'));
            testCase.Config = load_compiler_config(fullfile( ...
                testCase.BaseDir, 'configs', 'compiler_config.example.json'));
        end
    end

    methods (Test)
        function testM1PassesThresholdControlsAndRequiresZeroW(testCase)
            raw = struct('c0', 0.04, 'c1', 0.10, 'c2', 0.20, 'w', 0);
            projected = project_method_constraints('M1', raw, testCase.Config);

            testCase.verifyEqual( ...
                [projected.c0, projected.c1, projected.c2, projected.w], ...
                [0.04, 0.10, 0.20, 0]);
            testCase.verifyFalse(projected.projection_applied);
            testCase.verifyEqual(projected.projection_l2, 0);
            testCase.verifyTrue(isnan(projected.c_projected));

            raw.w = 4;
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints('M1', raw, testCase.Config), ...
                'MATLABGyroid:MethodConstraint', 'M1 requires w=0');
        end

        function testM2UsesOrthogonalMeanProjection(testCase)
            raw = struct('c0', 0.04, 'c1', 0.10, 'c2', 0.16, 'w', 4);
            projected = project_method_constraints('M2', raw, testCase.Config);

            testCase.verifyEqual( ...
                [projected.c0, projected.c1, projected.c2, ...
                projected.c_projected], [0.10, 0.10, 0.10, 0.10], ...
                'AbsTol', 10 * eps);
            testCase.verifyEqual(projected.w, 4);
            testCase.verifyEqual(projected.projection_l2, ...
                norm([-0.06, 0, 0.06]), 'AbsTol', 10 * eps);
            testCase.verifyTrue(projected.projection_applied);
            testCase.verifyEqual(projected.raw_parameters, raw);
        end

        function testM2EqualControlsRecordNoProjectionChange(testCase)
            raw = struct('c0', 0.10, 'c1', 0.10, 'c2', 0.10, 'w', 4);
            projected = project_method_constraints('M2', raw, testCase.Config);

            testCase.verifyFalse(projected.projection_applied);
            testCase.verifyEqual(projected.projection_l2, 0, ...
                'AbsTol', 10 * eps);
        end

        function testM3PassesAllControls(testCase)
            raw = struct('c0', 0.03, 'c1', 0.10, 'c2', 0.20, 'w', 4);
            projected = project_method_constraints('M3', raw, testCase.Config);

            testCase.verifyEqual( ...
                [projected.c0, projected.c1, projected.c2, projected.w], ...
                [0.03, 0.10, 0.20, 4]);
            testCase.verifyFalse(projected.projection_applied);
            testCase.verifyEqual(projected.projection_l2, 0);
            testCase.verifyTrue(isnan(projected.c_projected));
        end

        function testUnknownMethodRejected(testCase)
            raw = struct('c0', 0.10, 'c1', 0.10, 'c2', 0.10, 'w', 0);
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints('M4', raw, testCase.Config), ...
                'MATLABGyroid:InvalidRequest', 'method must be one of');
        end

        function testMethodMustBeTextScalar(testCase)
            raw = struct('c0', 0.10, 'c1', 0.10, 'c2', 0.10, 'w', 0);
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints(struct('bad', true), raw, ...
                testCase.Config), 'MATLABGyroid:InvalidRequest', ...
                'method must be a character row vector or string scalar');
        end

        function testMissingParameterRejected(testCase)
            raw = struct('c0', 0.10, 'c1', 0.10, 'c2', 0.10);
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints('M1', raw, testCase.Config), ...
                'MATLABGyroid:InvalidRequest', ...
                'parameters must have fields {c0, c1, c2, w}');
        end

        function testExtraParameterRejected(testCase)
            raw = struct('c0', 0.10, 'c1', 0.10, 'c2', 0.10, ...
                'w', 0, 'unused', 1);
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints('M1', raw, testCase.Config), ...
                'MATLABGyroid:InvalidRequest', ...
                'parameters must have fields {c0, c1, c2, w}');
        end

        function testStructArrayParametersRejected(testCase)
            raw = repmat( ...
                struct('c0', 0.10, 'c1', 0.10, 'c2', 0.10, 'w', 0), ...
                1, 2);
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints('M1', raw, testCase.Config), ...
                'MATLABGyroid:InvalidRequest', ...
                'parameters must be a scalar struct');
        end

        function testNonFiniteAndNonScalarControlsRejected(testCase)
            cases = { ...
                struct('c0', NaN, 'c1', 0.10, 'c2', 0.10, 'w', 0), 'c0'; ...
                struct('c0', 0.10, 'c1', Inf, 'c2', 0.10, 'w', 0), 'c1'; ...
                struct('c0', 0.10, 'c1', 0.10, 'c2', [0.1, 0.2], 'w', 0), 'c2'; ...
                struct('c0', 0.10, 'c1', 0.10, 'c2', 0.10, 'w', 1i), 'w'};
            for caseIndex = 1:size(cases, 1)
                TestFieldKernel.verifyFailure(testCase, ...
                    @() project_method_constraints('M1', cases{caseIndex, 1}, ...
                    testCase.Config), 'MATLABGyroid:InvalidRequest', ...
                    sprintf('parameters.%s must be a finite real numeric scalar', ...
                    cases{caseIndex, 2}));
            end
        end

        function testM1ClosedThresholdBoundsEnforced(testCase)
            atBounds = struct('c0', 0.03, 'c1', 0.10, 'c2', 0.20, 'w', 0);
            project_method_constraints('M1', atBounds, testCase.Config);

            atBounds.c0 = 0.03 - 1e-6;
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints('M1', atBounds, testCase.Config), ...
                'MATLABGyroid:OutOfBounds', 'M1.c0');
            atBounds.c0 = 0.03;
            atBounds.c2 = 0.20 + 1e-6;
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints('M1', atBounds, testCase.Config), ...
                'MATLABGyroid:OutOfBounds', 'M1.c2');
        end

        function testM2ProjectedThresholdBoundEnforced(testCase)
            raw = struct('c0', 0.01, 'c1', 0.01, 'c2', 0.01, 'w', 4);
            TestFieldKernel.verifyFailure(testCase, ...
                @() project_method_constraints('M2', raw, testCase.Config), ...
                'MATLABGyroid:OutOfBounds', 'M2.c_projected');
        end

        function testOpenWEndpointsRejectedForM2AndM3(testCase)
            for method = {'M2', 'M3'}
                raw = struct('c0', 0.10, 'c1', 0.10, 'c2', 0.10, 'w', 2);
                TestFieldKernel.verifyFailure(testCase, ...
                    @() project_method_constraints(method{1}, raw, testCase.Config), ...
                    'MATLABGyroid:OutOfBounds', sprintf('%s.w', method{1}));
                raw.w = 8;
                TestFieldKernel.verifyFailure(testCase, ...
                    @() project_method_constraints(method{1}, raw, testCase.Config), ...
                    'MATLABGyroid:OutOfBounds', sprintf('%s.w', method{1}));
            end
        end

        function testThresholdProfileHitsAllKnotsExactly(testCase)
            projected = project_method_constraints('M1', ...
                struct('c0', 0.04, 'c1', 0.10, 'c2', 0.20, 'w', 0), ...
                testCase.Config);

            testCase.verifyEqual( ...
                evaluate_threshold_profile([0, 1, 2], projected), ...
                [0.04, 0.10, 0.20], 'AbsTol', 10 * eps);
            testCase.verifyEqual( ...
                evaluate_threshold_profile([0; 1; 2], projected), ...
                [0.04; 0.10; 0.20], 'AbsTol', 10 * eps);
        end

        function testThresholdProfileUsesBothLinearSegments(testCase)
            projected = project_method_constraints('M3', ...
                struct('c0', 0.04, 'c1', 0.10, 'c2', 0.20, 'w', 4), ...
                testCase.Config);
            zOverL = [0.5, 1 - 1e-9, 1, 1 + 1e-9, 1.5];
            expected = [0.07, 0.10 - 0.06e-9, 0.10, ...
                0.10 + 0.10e-9, 0.15];

            testCase.verifyEqual( ...
                evaluate_threshold_profile(zOverL, projected), expected, ...
                'AbsTol', 100 * eps);
        end

        function testM2ThresholdIsProjectedConstant(testCase)
            projected = project_method_constraints('M2', ...
                struct('c0', 0.04, 'c1', 0.10, 'c2', 0.16, 'w', 4), ...
                testCase.Config);

            testCase.verifyEqual( ...
                evaluate_threshold_profile([0, 0.5, 1, 2], projected), ...
                0.10 * ones(1, 4), 'AbsTol', 10 * eps);
        end

        function testM1CellSizeProfileIsConstant(testCase)
            projected = project_method_constraints('M1', ...
                struct('c0', 0.04, 'c1', 0.10, 'c2', 0.20, 'w', 0), ...
                testCase.Config);

            gamma = evaluate_cell_size_profile( ...
                [0, 0.5, 1, 2], projected, testCase.Config);
            testCase.verifyEqual(gamma, 1.5 * ones(1, 4), ...
                'AbsTol', 10 * eps);
        end

        function testDenominatorCellSizeProfileIsExact(testCase)
            for method = {'M2', 'M3'}
                projected = project_method_constraints(method{1}, ...
                    struct('c0', 0.04, 'c1', 0.10, 'c2', 0.16, 'w', 4), ...
                    testCase.Config);
                gamma = evaluate_cell_size_profile( ...
                    [0, 1, 2], projected, testCase.Config);
                testCase.verifyEqual(gamma, [1.5, 1.75, 2.0], ...
                    'AbsTol', 10 * eps);
            end
        end

        function testCellSizeProfilePreservesColumnOrientation(testCase)
            projected = project_method_constraints('M3', ...
                struct('c0', 0.04, 'c1', 0.10, 'c2', 0.16, 'w', 4), ...
                testCase.Config);

            gamma = evaluate_cell_size_profile( ...
                [0; 1; 2], projected, testCase.Config);
            testCase.verifySize(gamma, [3, 1]);
            testCase.verifyEqual(gamma, [1.5; 1.75; 2.0], ...
                'AbsTol', 10 * eps);
        end

        function testInvalidProfileCoordinatesRejected(testCase)
            projected = project_method_constraints('M3', ...
                struct('c0', 0.04, 'c1', 0.10, 'c2', 0.16, 'w', 4), ...
                testCase.Config);
            invalidValues = {[], NaN, Inf, 1i, [0, 1; 1, 2]};
            for valueIndex = 1:numel(invalidValues)
                value = invalidValues{valueIndex};
                TestFieldKernel.verifyFailure(testCase, ...
                    @() evaluate_threshold_profile(value, projected), ...
                    'MATLABGyroid:InvalidGeometry', ...
                    'z_over_l must be a non-empty finite real numeric vector');
                TestFieldKernel.verifyFailure(testCase, ...
                    @() evaluate_cell_size_profile( ...
                    value, projected, testCase.Config), ...
                    'MATLABGyroid:InvalidGeometry', ...
                    'z_over_l must be a non-empty finite real numeric vector');
            end
        end

        function testOutOfDomainProfileCoordinatesRejected(testCase)
            projected = project_method_constraints('M3', ...
                struct('c0', 0.04, 'c1', 0.10, 'c2', 0.16, 'w', 4), ...
                testCase.Config);
            for value = {-eps, 2 + eps(2)}
                TestFieldKernel.verifyFailure(testCase, ...
                    @() evaluate_threshold_profile(value{1}, projected), ...
                    'MATLABGyroid:InvalidGeometry', ...
                    'z_over_l must lie within [0, 2]');
                TestFieldKernel.verifyFailure(testCase, ...
                    @() evaluate_cell_size_profile( ...
                    value{1}, projected, testCase.Config), ...
                    'MATLABGyroid:InvalidGeometry', ...
                    'z_over_l must lie within [0, 2]');
            end
        end

        function testFieldGridIncludesDomainEndpoints(testCase)
            projected = TestFieldKernel.projectExample( ...
                testCase, 'M1', [0.04, 0.10, 0.20, 0]);
            field = build_graded_gyroid_field( ...
                projected, testCase.Config, 8);

            testCase.verifySize(field.G, [9, 9, 17]);
            testCase.verifyEqual(field.x_over_l([1, end]), [0, 1], ...
                'AbsTol', eps);
            testCase.verifyEqual(field.y_over_l([1, end]), [0, 1], ...
                'AbsTol', eps);
            testCase.verifyEqual(field.z_over_l([1, end]), [0, 2], ...
                'AbsTol', eps);
            testCase.verifyEqual(field.spacing_over_l, 1 / 8, ...
                'AbsTol', eps);
            testCase.verifyEqual(field.spacing_mm, ...
                testCase.Config.reference_length_mm / 8, 'AbsTol', eps);
            testCase.verifyEqual(field.resolution, 8);
            testCase.verifyEqual(field.method, 'M1');
        end

        function testKnownGyroidPointEqualsOne(testCase)
            projected = TestFieldKernel.projectExample( ...
                testCase, 'M1', [0.10, 0.10, 0.10, 0]);
            field = build_graded_gyroid_field( ...
                projected, testCase.Config, 8);

            testCase.verifyEqual(field.G(3, 1, 1), 1, ...
                'AbsTol', 100 * eps);
        end

        function testFieldProfilesMatchProfileEvaluators(testCase)
            for method = {'M1', 'M2', 'M3'}
                if strcmp(method{1}, 'M1')
                    values = [0.04, 0.10, 0.16, 0];
                else
                    values = [0.04, 0.10, 0.16, 4];
                end
                projected = TestFieldKernel.projectExample( ...
                    testCase, method{1}, values);
                field = build_graded_gyroid_field( ...
                    projected, testCase.Config, 8);

                testCase.verifyEqual(field.threshold, ...
                    evaluate_threshold_profile(field.z_over_l, projected));
                testCase.verifyEqual(field.cell_size_over_l, ...
                    evaluate_cell_size_profile( ...
                    field.z_over_l, projected, testCase.Config));
            end
        end

        function testFieldIsFiniteRealAndDeterministic(testCase)
            projected = TestFieldKernel.projectExample( ...
                testCase, 'M3', [0.04, 0.10, 0.16, 4]);
            first = build_graded_gyroid_field( ...
                projected, testCase.Config, 8);
            second = build_graded_gyroid_field( ...
                projected, testCase.Config, 8);

            testCase.verifyTrue(isreal(first.G));
            testCase.verifyTrue(all(isfinite(first.G(:))));
            testCase.verifyEqual(first.G, second.G);
            testCase.verifyEqual(first.threshold, second.threshold);
            testCase.verifyEqual( ...
                first.cell_size_over_l, second.cell_size_over_l);
        end

        function testInvalidFieldResolutionRejected(testCase)
            projected = TestFieldKernel.projectExample( ...
                testCase, 'M1', [0.04, 0.10, 0.16, 0]);
            invalidValues = {0, -1, 8.5, NaN, Inf, 1i, [8, 8], 193};
            for valueIndex = 1:numel(invalidValues)
                TestFieldKernel.verifyFailure(testCase, ...
                    @() build_graded_gyroid_field(projected, ...
                    testCase.Config, invalidValues{valueIndex}), ...
                    'MATLABGyroid:InvalidGeometry', ...
                    'resolution must be a positive integer no greater than');
            end
        end

        function testNonIntegralGridIntervalCountRejected(testCase)
            projected = TestFieldKernel.projectExample( ...
                testCase, 'M1', [0.04, 0.10, 0.16, 0]);
            modifiedConfig = testCase.Config;
            modifiedConfig.geometry_parameters.domain_over_l.x = [0, 1.1];

            TestFieldKernel.verifyFailure(testCase, ...
                @() build_graded_gyroid_field( ...
                projected, modifiedConfig, 8), ...
                'MATLABGyroid:InvalidGeometry', ...
                'domain spans times resolution must be integers');
        end

        function testValidMethodFieldsProduceMixedSheetVolumes(testCase)
            cases = { ...
                'M1', [0.04, 0.10, 0.16, 0]; ...
                'M2', [0.04, 0.10, 0.16, 4]; ...
                'M3', [0.04, 0.10, 0.16, 4]};
            for caseIndex = 1:size(cases, 1)
                projected = TestFieldKernel.projectExample( ...
                    testCase, cases{caseIndex, 1}, cases{caseIndex, 2});
                field = build_graded_gyroid_field( ...
                    projected, testCase.Config, 16);
                volume = build_solid_volume(field, testCase.Config);

                expected = abs(field.G) <= reshape( ...
                    field.threshold, 1, 1, []);
                testCase.verifyClass(volume.solid, 'logical');
                testCase.verifySize(volume.solid, size(field.G));
                testCase.verifyEqual(volume.solid, expected);
                testCase.verifyGreaterThan(volume.solid_fraction, 0);
                testCase.verifyLessThan(volume.solid_fraction, 1);
                testCase.verifyEqual(volume.solid_count, nnz(expected));
                testCase.verifyEqual(volume.void_count, ...
                    numel(expected) - nnz(expected));
                testCase.verifyEqual(volume.voxel_count, numel(expected));
                testCase.verifyEqual(volume.convention, 'sheet_band');
            end
        end

        function testEmptyAndFullSheetVolumesRejected(testCase)
            emptyField = struct('G', ones(2, 2, 2), ...
                'threshold', [0, 0]);
            TestFieldKernel.verifyFailure(testCase, ...
                @() build_solid_volume(emptyField, testCase.Config), ...
                'MATLABGyroid:EmptySolid', 'sheet-band volume contains no solid voxels');

            fullField = struct('G', zeros(2, 2, 2), ...
                'threshold', [0.1, 0.1]);
            TestFieldKernel.verifyFailure(testCase, ...
                @() build_solid_volume(fullField, testCase.Config), ...
                'MATLABGyroid:FullSolid', 'sheet-band volume contains no void voxels');
        end

        function testInvalidSolidInputsRejected(testCase)
            validField = struct('G', ones(2, 2, 2), ...
                'threshold', [0.1, 0.1]);

            badConvention = testCase.Config;
            badConvention.solid_convention = 'signed_level_set';
            TestFieldKernel.verifyFailure(testCase, ...
                @() build_solid_volume(validField, badConvention), ...
                'MATLABGyroid:InvalidGeometry', ...
                'solid_convention must be "sheet_band"');

            nonFiniteField = validField;
            nonFiniteField.G(1) = NaN;
            TestFieldKernel.verifyFailure(testCase, ...
                @() build_solid_volume(nonFiniteField, testCase.Config), ...
                'MATLABGyroid:InvalidGeometry', ...
                'field.G must be a non-empty finite real numeric array');

            wrongThresholdLength = validField;
            wrongThresholdLength.threshold = 0.1;
            TestFieldKernel.verifyFailure(testCase, ...
                @() build_solid_volume(wrongThresholdLength, testCase.Config), ...
                'MATLABGyroid:InvalidGeometry', ...
                'field.threshold length must equal size(field.G, 3)');

            negativeThreshold = validField;
            negativeThreshold.threshold = [-0.1, 0.1];
            TestFieldKernel.verifyFailure(testCase, ...
                @() build_solid_volume(negativeThreshold, testCase.Config), ...
                'MATLABGyroid:InvalidGeometry', ...
                'field.threshold must contain finite nonnegative values');
        end

        function testKernelProvenanceLabelsAreFrozen(testCase)
            contract = compiler_contract();
            testCase.verifyEqual(contract.thresholdProfile, ...
                'piecewise_linear_knots_z_over_l_0_1_2');
            testCase.verifyEqual(contract.cellSizeProfile, ...
                'gamma(z_over_l)=1.5+z_over_l/w');
            testCase.verifyEqual(contract.gyroidFieldVersion, ...
                'small-si-s6-s9-candidate-v1');
            testCase.verifyEqual(contract.solidConvention, 'sheet_band');
        end
    end

    methods (Static, Access = private)
        function projected = projectExample(testCase, method, values)
            raw = struct('c0', values(1), 'c1', values(2), ...
                'c2', values(3), 'w', values(4));
            projected = project_method_constraints( ...
                method, raw, testCase.Config);
        end

        function verifyFailure(testCase, action, expectedId, messageFragment)
            caughtException = [];
            try
                action();
            catch caught
                caughtException = caught;
            end
            testCase.assertNotEmpty(caughtException, ...
                sprintf('Expected %s containing "%s".', ...
                expectedId, messageFragment));
            testCase.verifyEqual(caughtException.identifier, expectedId);
            testCase.verifyTrue(contains(caughtException.message, messageFragment), ...
                sprintf('Actual message: %s', caughtException.message));
        end
    end
end
