function response = run_geometry_compiler(requestPath, responsePath)
%RUN_GEOMETRY_COMPILER Compile one M03 request into audited artifacts.

    baseDirectory = fileparts(mfilename('fullpath'));
    addpath(fullfile(baseDirectory, 'core'));
    responsePath = validate_text_scalar(responsePath, 'response_path', ...
        'MATLABGyroid:InvalidRequest');
    if exist(responsePath, 'file') ~= 0 || ...
            exist(responsePath, 'dir') ~= 0
        throw(MException('MATLABGyroid:OutputConflict', ...
            'refusing to overwrite response JSON leaf: %s', responsePath));
    end
    contract = compiler_contract();
    response = base_response(contract);
    createdStl = '';
    createdManifest = '';
    request = [];
    try
        configPath = fullfile(baseDirectory, 'configs', ...
            'compiler_config.example.json');
        config = load_compiler_config(configPath);
        config.compiler_config_sha256 = sha256_file(configPath, ...
            'MATLABGyroid:InvalidConfig', 'compiler config');
        request = parse_and_validate_request(requestPath, config);
        response.request_id = request.request_id;
        response.requested_parameters = request.requested_parameters;
        response.effective_parameters = request.effective_parameters;
        if exist(request.output_dir, 'dir') ~= 7
            [made, message] = mkdir(request.output_dir);
            if ~made
                throw(MException('MATLABGyroid:OutputError', ...
                    'cannot create output directory: %s', message));
            end
        end

        field = build_finite_csg_field(request.effective_parameters, ...
            config, request.resolution, true);
        response.diagnostics = field_diagnostics(field);
        mesh = extract_isosurface_mesh(field, contract.isosurfaceLevel);
        [meshReport, validatedMesh] = validate_surface_mesh( ...
            mesh, field.spacing_mm, config.mesh_qc);
        meshReport.solid_connectivity = field.solid_connectivity;
        meshReport.solid_component_count = field.solid_component_count;
        meshReport.void_connectivity = field.void_connectivity;
        meshReport.void_component_count = field.void_component_count;
        response.mesh_qc = meshReport;
        if ~meshReport.valid
            throw(MException(['MATLABGyroid:', meshReport.failure_code], ...
                'surface mesh failed M03 gate: %s', ...
                meshReport.failure_code));
        end
        if field.solid_component_count ~= 1
            throw(MException('MATLABGyroid:DISCONNECTED_SOLID', ...
                'sampled solid has %d components under %d-connectivity', ...
                field.solid_component_count, field.solid_connectivity));
        end

        draftManifest = build_geometry_manifest(request, config, ...
            field, meshReport, struct());
        geometryHash = draftManifest.geometry_identity_sha256;
        stlPath = fullfile(request.output_dir, ...
            ['geometry_', geometryHash, '.stl']);
        manifestPath = fullfile(request.output_dir, ...
            ['geometry_', geometryHash, '.manifest.json']);
        artifactSummary = export_binary_stl(validatedMesh, stlPath);
        createdStl = stlPath;
        artifact = struct('stl_path', stlPath, ...
            'byte_length', artifactSummary.byte_length, ...
            'triangle_count', artifactSummary.triangle_count, ...
            'all_finite', artifactSummary.all_finite, ...
            'sha256', artifactSummary.sha256);
        manifest = build_geometry_manifest(request, config, ...
            field, meshReport, artifact);
        write_json_atomic(manifest, manifestPath);
        createdManifest = manifestPath;
        manifestSha256 = sha256_file(manifestPath, ...
            'MATLABGyroid:OutputError', 'published geometry manifest');

        response.valid = true;
        response.failure_code = '';
        response.failure_message = '';
        response.geometry_identity_sha256 = geometryHash;
        response.artifacts = struct('stl_path', stlPath, ...
            'manifest_path', manifestPath, ...
            'manifest_sha256', manifestSha256, ...
            'stl_sha256', artifactSummary.sha256, ...
            'stl_byte_length', artifactSummary.byte_length, ...
            'triangle_count', artifactSummary.triangle_count);
        write_json_atomic(response, responsePath);
    catch cause
        delete_owned_file(createdManifest);
        delete_owned_file(createdStl);
        response.valid = false;
        response.failure_code = map_failure_code(cause.identifier);
        response.failure_message = cause.message;
        if ~isempty(request)
            response.request_id = request.request_id;
            response.requested_parameters = request.requested_parameters;
            response.effective_parameters = request.effective_parameters;
        end
        if exist(responsePath, 'file') ~= 2
            write_json_atomic(response, responsePath);
        end
    end
end

function response = base_response(contract)
    response = struct('schema_version', '1.0', ...
        'request_id', '', 'compiler_version', compiler_version(), ...
        'validation_stage', contract.validationStage, 'valid', false, ...
        'failure_code', '', 'failure_message', '', ...
        'geometry_definition', contract.geometryDefinition, ...
        'requested_parameters', struct(), ...
        'effective_parameters', struct(), 'diagnostics', struct(), ...
        'mesh_qc', struct(), ...
        'geometry_identity_sha256', '', 'artifacts', struct(), ...
        'descriptors', 'not_computed', ...
        'abaqus_gate0', 'not_computed', ...
        'printability', 'not_computed', ...
        'experiment', 'not_computed');
end

function diagnostics = field_diagnostics(field)
    diagnostics = struct( ...
        'interior_cell_count', field.interior_cell_count, ...
        'interior_solid_count', field.interior_solid_count, ...
        'interior_void_count', field.interior_void_count, ...
        'interior_solid_fraction', field.interior_solid_fraction, ...
        'solid_connectivity', field.solid_connectivity, ...
        'solid_component_count', field.solid_component_count, ...
        'void_connectivity', field.void_connectivity, ...
        'void_component_count', field.void_component_count);
end

function code = map_failure_code(identifier)
    mappings = { ...
        'MATLABGyroid:InvalidRequest', 'INVALID_REQUEST'; ...
        'MATLABGyroid:MethodConstraint', 'METHOD_CONSTRAINT'; ...
        'MATLABGyroid:OutOfBounds', 'OUT_OF_BOUNDS'; ...
        'MATLABGyroid:EmptySolid', 'EMPTY_SOLID'; ...
        'MATLABGyroid:FullSolid', 'FULL_SOLID'; ...
        'MATLABGyroid:NonfiniteField', 'NONFINITE_FIELD'; ...
        'MATLABGyroid:EmptyMesh', 'EMPTY_MESH'; ...
        'MATLABGyroid:OutputConflict', 'OUTPUT_CONFLICT'; ...
        'MATLABGyroid:STLSerializationError', 'STL_SERIALIZATION_ERROR'; ...
        'MATLABGyroid:STLVerificationError', 'STL_VERIFICATION_ERROR'};
    match = strcmp(mappings(:, 1), identifier);
    if any(match)
        code = mappings{find(match, 1), 2};
        return;
    end
    prefix = 'MATLABGyroid:';
    if startsWith(identifier, prefix)
        candidate = extractAfter(identifier, strlength(prefix));
        allowed = {'DISCONNECTED_SOLID', 'DEGENERATE_MESH', ...
            'OPEN_MESH', 'NONMANIFOLD_MESH', ...
            'INCONSISTENT_ORIENTATION', 'SELF_INTERSECTION', ...
            'SELF_INTERSECTION_CHECK_UNAVAILABLE', 'DUPLICATE_FACE'};
        if ismember(candidate, allowed)
            code = char(candidate);
            return;
        end
    end
    code = 'INTERNAL_ERROR';
end

function delete_owned_file(path)
    if ~isempty(path) && exist(path, 'file') == 2
        delete(path);
    end
end
