function manifest = build_geometry_manifest( ...
        request, config, field, meshReport, artifact)
%BUILD_GEOMETRY_MANIFEST Build stable M03 provenance and geometry identity.

    contract = compiler_contract();
    effective = request.effective_parameters;
    domain = config.geometry_parameters.domain_over_l;
    canonical = sprintf([ ...
        'compiler_version=%s\ngeometry_definition=%s\nmethod=%s\n' ...
        'c0=%.17g\nc1=%.17g\nc2=%.17g\nw=%.17g\n' ...
        'domain_x=%.17g,%.17g\ndomain_y=%.17g,%.17g\n' ...
        'domain_z=%.17g,%.17g\nreference_length_mm=%.17g\n' ...
        'resolution=%d\nbeta_box=%.17g\nisosurface_level=%.17g\n' ...
        'compiler_config_sha256=%s\ndescriptor_definition_sha256=%s\n' ...
        'parameter_domain_manifest_sha256=%s\n'], ...
        compiler_version(), contract.geometryDefinition, request.method, ...
        effective.c0, effective.c1, effective.c2, effective.w, ...
        domain.x(1), domain.x(2), domain.y(1), domain.y(2), ...
        domain.z(1), domain.z(2), config.reference_length_mm, ...
        request.resolution, contract.betaBox, contract.isosurfaceLevel, ...
        config.compiler_config_sha256, ...
        config.descriptor_definition_sha256, ...
        config.parameter_domain_manifest_sha256);
    geometryHash = sha256_text(canonical);
    requestSummary = struct('request_id', request.request_id, ...
        'raw_request_sha256', request.raw_request_sha256, ...
        'request_semantic_sha256', request.request_semantic_sha256, ...
        'requested_parameters', request.requested_parameters, ...
        'effective_parameters', request.effective_parameters);
    discretization = struct('resolution', request.resolution, ...
        'spacing_over_l', field.spacing_over_l, ...
        'spacing_mm', field.spacing_mm, ...
        'exterior_margin_mm', field.exterior_margin_mm, ...
        'solid_connectivity', field.solid_connectivity, ...
        'solid_component_count', field.solid_component_count, ...
        'beta_box', field.beta_box, ...
        'isosurface_level', field.isosurface_level, ...
        'grid_convention', field.grid_convention, ...
        'units', 'mm');
    manifest = struct('schema_version', '1.0', ...
        'validation_stage', contract.validationStage, ...
        'compiler_version', compiler_version(), ...
        'geometry_definition', contract.geometryDefinition, ...
        'request', requestSummary, ...
        'geometry_identity_sha256', geometryHash, ...
        'geometry_identity_canonical_text', canonical, ...
        'discretization', discretization, ...
        'mesh_qc', meshReport, 'artifact', artifact, ...
        'deferred_stages', {{'M04_DESCRIPTORS', 'ABAQUS_GATE0', ...
        'PRINTABILITY', 'EXPERIMENT'}});
end
