function field = build_legacy_descriptor_field( ...
        projected, config, samplesPerReferenceLength, referenceLengthMm)
%BUILD_LEGACY_DESCRIPTOR_FIELD Sample the endpoint-grid legacy TPMS field.

    errorId = 'MATLABGyroid:DescriptorProfileInvalid';
    validateattributes(samplesPerReferenceLength, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive', 'integer'}, mfilename, ...
        'samplesPerReferenceLength');
    validateattributes(referenceLengthMm, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, mfilename, ...
        'referenceLengthMm');
    validate_config(config, errorId);

    domain = config.geometry_parameters.domain_over_l;
    spans = [diff(domain.x), diff(domain.y), diff(domain.z)];
    intervalCounts = spans .* double(samplesPerReferenceLength);
    tolerance = 16 * eps(max(1, max(abs(intervalCounts))));
    if any(abs(intervalCounts - round(intervalCounts)) > tolerance)
        throw(MException(errorId, ...
            'legacy endpoint-grid spans must contain integer intervals'));
    end
    intervalCounts = round(intervalCounts);
    xOverL = linspace(domain.x(1), domain.x(2), intervalCounts(1) + 1);
    yOverL = linspace(domain.y(1), domain.y(2), intervalCounts(2) + 1);
    zOverL = linspace(domain.z(1), domain.z(2), intervalCounts(3) + 1);
    sampled = evaluate_continuous_graded_gyroid(projected, config, ...
        xOverL, yOverL, zOverL);
    sheetField = abs(sampled.G) - reshape(sampled.threshold, 1, 1, []);
    if ~isreal(sheetField) || any(~isfinite(sheetField(:)))
        throw(MException(errorId, ...
            'legacy endpoint-grid implicit field must be finite and real'));
    end

    xMm = xOverL .* double(referenceLengthMm);
    yMm = yOverL .* double(referenceLengthMm);
    zMm = zOverL .* double(referenceLengthMm);
    mesh = isosurface(xMm, yMm, zMm, sheetField, 0);
    [surfaceAreaMm2, triangleCount] = surface_area(mesh, errorId);
    solid = sheetField <= 0;
    if ~any(solid(:)) || ~any(~solid(:))
        throw(MException(errorId, ...
            'legacy endpoint-grid volume must contain both solid and void'));
    end

    field = struct('solid', solid, ...
        'voxel_size_mm', double(referenceLengthMm) / ...
        double(samplesPerReferenceLength), ...
        'surface_area_mm2', surfaceAreaMm2, ...
        'bounds_mm', struct('x', [xMm(1), xMm(end)], ...
        'y', [yMm(1), yMm(end)], 'z', [zMm(1), zMm(end)]), ...
        'samples_per_reference_length', double(samplesPerReferenceLength), ...
        'reference_length_mm', double(referenceLengthMm), ...
        'axes_over_l', struct('x', xOverL, 'y', yOverL, 'z', zOverL), ...
        'triangle_count', triangleCount);
end

function validate_config(config, errorId)
    if ~isstruct(config) || ~isscalar(config) || ...
            ~isfield(config, 'geometry_parameters') || ...
            ~isstruct(config.geometry_parameters) || ...
            ~isscalar(config.geometry_parameters) || ...
            ~isfield(config.geometry_parameters, 'domain_over_l')
        throw(MException(errorId, ...
            'config must contain geometry_parameters.domain_over_l'));
    end
    domain = config.geometry_parameters.domain_over_l;
    if ~isstruct(domain) || ~isscalar(domain) || ...
            ~all(isfield(domain, {'x', 'y', 'z'}))
        throw(MException(errorId, ...
            'config geometry_parameters.domain_over_l must contain x, y, and z'));
    end
    for name = {'x', 'y', 'z'}
        axisName = name{1};
        bounds = domain.(axisName);
        if ~isnumeric(bounds) || ~isreal(bounds) || numel(bounds) ~= 2 || ...
                any(~isfinite(bounds(:))) || bounds(1) >= bounds(2)
            throw(MException(errorId, ...
                'legacy domain %s must be a finite increasing pair', axisName));
        end
    end
end

function [surfaceAreaMm2, triangleCount] = surface_area(mesh, errorId)
    if ~isstruct(mesh) || ~isfield(mesh, 'vertices') || ~isfield(mesh, 'faces') || ...
            isempty(mesh.vertices) || isempty(mesh.faces)
        throw(MException(errorId, ...
            'legacy endpoint-grid isosurface must contain faces and vertices'));
    end
    vertices = double(mesh.vertices);
    faces = double(mesh.faces);
    if size(vertices, 2) ~= 3 || size(faces, 2) ~= 3 || ...
            any(~isfinite(vertices(:))) || any(faces(:) < 1) || ...
            any(faces(:) > size(vertices, 1)) || any(mod(faces(:), 1) ~= 0)
        throw(MException(errorId, 'legacy endpoint-grid isosurface is invalid'));
    end
    edgeOne = vertices(faces(:, 2), :) - vertices(faces(:, 1), :);
    edgeTwo = vertices(faces(:, 3), :) - vertices(faces(:, 1), :);
    triangleAreas = 0.5 .* vecnorm(cross(edgeOne, edgeTwo, 2), 2, 2);
    surfaceAreaMm2 = sum(triangleAreas);
    if ~isfinite(surfaceAreaMm2) || surfaceAreaMm2 <= 0
        throw(MException(errorId, ...
            'legacy endpoint-grid surface area must be finite and positive'));
    end
    triangleCount = size(faces, 1);
end
