function result = compute_legacy_small_descriptors(field, definitionSha256)
%COMPUTE_LEGACY_SMALL_DESCRIPTORS Compute TPMS-Designer-compatible metrics.

    errorId = 'MATLABGyroid:DescriptorProfileInvalid';
    validate_field(field, errorId);
    validate_hash(definitionSha256, errorId);
    solid = field.solid;
    [sx, sy, sz] = size(solid);
    voxelSizeMm = double(field.voxel_size_mm);
    bounds = field.bounds_mm;
    dimensions = [diff(bounds.x), diff(bounds.y), diff(bounds.z)];

    values = struct();
    values.relativeVolume = nnz(solid(1:sx-1, 1:sy-1, 1:sz-1)) / ...
        ((sx - 1) * (sy - 1) * (sz - 1));
    values.relativeArea = double(field.surface_area_mm2) / ...
        (2 * (dimensions(1) * dimensions(2) + ...
        dimensions(2) * dimensions(3) + dimensions(3) * dimensions(1)));

    % TPMS-Designer a5f7d59b59f5c00e0f50c0bc3675f38f553454eb
    % classes/metrics.m: circularly extend all three endpoint-grid axes.
    paddedSolid = padarray(solid, size(solid), 'circular', 'both');
    solidBarrier = padarray(~paddedSolid, [1, 1, 1], true, 'both');
    values.thickness = 2 * voxelSizeMm * ...
        max(bwdist(solidBarrier), [], 'all');

    voidBarrier = padarray(paddedSolid, [1, 1, 1], true, 'both');
    values.poreDiameter = 2 * voxelSizeMm * ...
        max(bwdist(voidBarrier), [], 'all');
    sliceArea = squeeze(sum(solid, [1, 2])) .* voxelSizeMm^2;
    values.areaMean = mean(sliceArea);

    result = struct('profile', 'legacy_small', ...
        'definition_sha256', char(definitionSha256), ...
        'sampling', struct('grid_convention', 'endpoint_grid', ...
        'voxel_size_mm', voxelSizeMm, ...
        'samples_per_reference_length', ...
        double(field.samples_per_reference_length), ...
        'reference_length_mm', double(field.reference_length_mm), ...
        'periodic_padding_voxels', [sx, sy, sz]), ...
        'units', struct('relativeVolume', 'dimensionless', ...
        'relativeArea', 'dimensionless', 'thickness', 'mm', ...
        'poreDiameter', 'mm', 'areaMean', 'mm2'), ...
        'values', values, ...
        'diagnostics', struct('sample_size', [sx, sy, sz], ...
        'solid_voxel_count', nnz(solid), ...
        'void_voxel_count', nnz(~solid), ...
        'surface_area_mm2', double(field.surface_area_mm2), ...
        'surface_triangle_count', double(field.triangle_count)));
    validate_descriptor_result(result, 'legacy_small', char(definitionSha256));
end

function validate_field(field, errorId)
    required = {'solid', 'voxel_size_mm', 'surface_area_mm2', 'bounds_mm', ...
        'samples_per_reference_length', 'reference_length_mm', 'triangle_count'};
    if ~isstruct(field) || ~isscalar(field) || ~all(isfield(field, required))
        throw(MException(errorId, 'legacy descriptor field is incomplete'));
    end
    if ~islogical(field.solid) || ndims(field.solid) ~= 3 || ...
            any(size(field.solid) < 2, 'all') || ...
            ~any(field.solid(:)) || ~any(~field.solid(:))
        throw(MException(errorId, ...
            'legacy descriptor field solid mask must contain solid and void'));
    end
    validate_positive_scalar(field.voxel_size_mm, 'voxel_size_mm', errorId);
    validate_positive_scalar(field.surface_area_mm2, 'surface_area_mm2', errorId);
    validate_positive_scalar(field.samples_per_reference_length, ...
        'samples_per_reference_length', errorId);
    validate_positive_scalar(field.reference_length_mm, ...
        'reference_length_mm', errorId);
    if ~isnumeric(field.triangle_count) || ~isscalar(field.triangle_count) || ...
            ~isreal(field.triangle_count) || ~isfinite(field.triangle_count) || ...
            field.triangle_count <= 0 || mod(field.triangle_count, 1) ~= 0
        throw(MException(errorId, ...
            'legacy descriptor triangle_count must be a positive integer'));
    end
    if ~isstruct(field.bounds_mm) || ~isscalar(field.bounds_mm) || ...
            ~all(isfield(field.bounds_mm, {'x', 'y', 'z'}))
        throw(MException(errorId, 'legacy descriptor bounds_mm is invalid'));
    end
    for name = {'x', 'y', 'z'}
        axisName = name{1};
        bounds = field.bounds_mm.(axisName);
        if ~isnumeric(bounds) || ~isreal(bounds) || numel(bounds) ~= 2 || ...
                any(~isfinite(bounds(:))) || bounds(1) >= bounds(2)
            throw(MException(errorId, ...
                'legacy descriptor bounds_mm.%s is invalid', axisName));
        end
        expectedLength = (size(field.solid, axis_index(axisName)) - 1) * ...
            double(field.voxel_size_mm);
        if abs(diff(bounds) - expectedLength) > ...
                32 * eps(max(1, max(abs([diff(bounds), expectedLength]))))
            throw(MException(errorId, ...
                'legacy descriptor bounds_mm.%s conflicts with endpoint spacing', ...
                axisName));
        end
    end
end

function validate_positive_scalar(value, label, errorId)
    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value) || value <= 0
        throw(MException(errorId, ...
            'legacy descriptor %s must be a positive finite scalar', label));
    end
end

function index = axis_index(axisName)
    index = find(strcmp({'x', 'y', 'z'}, axisName), 1);
end

function validate_hash(value, errorId)
    if ~(ischar(value) && isrow(value)) && ~(isstring(value) && isscalar(value))
        throw(MException(errorId, 'definition_sha256 must be text'));
    end
    value = char(value);
    if isempty(regexp(value, '^[0-9a-f]{64}$', 'once'))
        throw(MException(errorId, ...
            'definition_sha256 must be 64 lowercase hexadecimal characters'));
    end
end
