function profiles = compute_descriptor_profiles(projected, config, ...
        resolution, validatedMesh, physicalBoundsMm)
%COMPUTE_DESCRIPTOR_PROFILES Compute independent legacy and physical profiles.

    legacyField = build_legacy_descriptor_field(projected, config, ...
        resolution, config.reference_length_mm);
    profiles = struct();
    profiles.legacy_small = compute_legacy_small_descriptors(legacyField, ...
        config.descriptor_profile_sha256.legacy_small);

    finiteField = build_finite_csg_field(projected, config, resolution, true);
    domain = config.geometry_parameters.domain_over_l;
    inside = { ...
        finiteField.x_over_l > domain.x(1) & finiteField.x_over_l < domain.x(2), ...
        finiteField.y_over_l > domain.y(1) & finiteField.y_over_l < domain.y(2), ...
        finiteField.z_over_l > domain.z(1) & finiteField.z_over_l < domain.z(2)};
    solid = finiteField.F(inside{1}, inside{2}, inside{3}) <= 0;
    profiles.physical_m04 = compute_physical_m04_descriptors(solid, ...
        finiteField.spacing_mm, validatedMesh, physicalBoundsMm, ...
        config.descriptor_profile_sha256.physical_m04);
end
