function calibration = calibrate_legacy_scale(selection, descriptorRunner, absoluteTolerance)
%CALIBRATE_LEGACY_SCALE Select one density and one global physical scale.

    errorId = 'MATLABGyroid:M04Gate0NotFrozen';
    selection = verify_small_gate0_selection(selection);
    if ~isa(descriptorRunner, 'function_handle')
        throw(MException(errorId, 'descriptorRunner must be a function handle'));
    end
    validateattributes(absoluteTolerance, {'numeric'}, ...
        {'scalar','real','finite','positive'});
    contract = legacy_calibration_contract();
    if absoluteTolerance ~= contract.absolute_tolerance
        throw(MException(errorId, ...
            'absoluteTolerance does not match the preregistered M04 value'));
    end
    candidateDensities = contract.candidate_densities;
    discovery = selection.rows(strcmp({selection.rows.role}, 'discovery'));
    densityResults = repmat(empty_density_result(), numel(candidateDensities), 1);
    cached = cell(numel(candidateDensities), numel(discovery));
    for densityIndex = 1:numel(candidateDensities)
        volumeErrors = zeros(1, numel(discovery));
        areaErrors = zeros(1, numel(discovery));
        for rowIndex = 1:numel(discovery)
            result = descriptorRunner(discovery(rowIndex), ...
                candidateDensities(densityIndex), 1);
            values = validate_values(result, errorId);
            cached{densityIndex, rowIndex} = values;
            archived = discovery(rowIndex).archived_descriptors;
            volumeErrors(rowIndex) = relative_error(values.relativeVolume, ...
                archived.relativeVolume, absoluteTolerance);
            areaErrors(rowIndex) = relative_error(values.relativeArea, ...
                archived.relativeArea, absoluteTolerance);
        end
        pooled = [volumeErrors, areaErrors];
        densityResults(densityIndex) = struct( ...
            'density', candidateDensities(densityIndex), ...
            'relativeVolume_median', median(volumeErrors), ...
            'relativeVolume_p95', deterministic_percentile(volumeErrors, .95), ...
            'relativeArea_median', median(areaErrors), ...
            'relativeArea_p95', deterministic_percentile(areaErrors, .95), ...
            'pooled_median', median(pooled), ...
            'pooled_p95', deterministic_percentile(pooled, .95), ...
            'eligible', within_threshold(median(volumeErrors), ...
            contract.median_threshold) && ...
            within_threshold(deterministic_percentile(volumeErrors, .95), ...
            contract.p95_threshold) && ...
            within_threshold(median(areaErrors), ...
            contract.median_threshold) && ...
            within_threshold(deterministic_percentile(areaErrors, .95), ...
            contract.p95_threshold));
    end
    calibration = base_calibration(selection, candidateDensities, densityResults, ...
        absoluteTolerance);
    eligible = find([densityResults.eligible]);
    if isempty(eligible)
        calibration.status = 'M04_SCALE_NOT_IDENTIFIED';
        return;
    end
    ranking = [[densityResults(eligible).pooled_median]', ...
        [densityResults(eligible).pooled_p95]', ...
        [densityResults(eligible).density]'];
    [~, rankOrder] = sortrows(ranking, [1, 2, 3]);
    selectedIndex = eligible(rankOrder(1));
    selectedDensity = candidateDensities(selectedIndex);

    estimates = zeros(numel(discovery), 3);
    discoveryTemplate = struct('row_id','','selection_digest','', ...
        'method','','excel_row',0,'archived',struct(), ...
        'computed_at_unit_length',struct());
    discoveryResults = repmat(discoveryTemplate, numel(discovery), 1);
    for rowIndex = 1:numel(discovery)
        computed = cached{selectedIndex, rowIndex};
        archived = discovery(rowIndex).archived_descriptors;
        if computed.thickness <= 0 || computed.poreDiameter <= 0 || ...
                computed.areaMean <= 0 || archived.thickness <= 0 || ...
                archived.poreDiameter <= 0 || archived.areaMean <= 0
            calibration.status = 'M04_SCALE_NOT_IDENTIFIED';
            return;
        end
        estimates(rowIndex, :) = [archived.thickness / computed.thickness, ...
            archived.poreDiameter / computed.poreDiameter, ...
            sqrt(archived.areaMean / computed.areaMean)];
        discoveryResults(rowIndex) = struct('row_id', discovery(rowIndex).row_id, ...
            'selection_digest', discovery(rowIndex).selection_digest, ...
            'method', discovery(rowIndex).method, ...
            'excel_row', discovery(rowIndex).excel_row, 'archived', archived, ...
            'computed_at_unit_length', computed);
    end
    if any(~isfinite(estimates(:))) || any(estimates(:) <= 0)
        calibration.status = 'M04_SCALE_NOT_IDENTIFIED';
        return;
    end
    frozenLength = median(estimates, 'all');
    relativeDeviation = abs(estimates - frozenLength) ./ frozenLength;
    groupMedians = median(estimates, 1);
    groupDeviation = abs(groupMedians - frozenLength) ./ frozenLength;
    statistics = struct('mard', median(relativeDeviation, 'all'), ...
        'p95', deterministic_percentile(relativeDeviation(:)', .95), ...
        'maximum', max(relativeDeviation, [], 'all'), ...
        'group_medians', groupMedians, ...
        'group_relative_deviation', groupDeviation, ...
        'estimates', estimates);
    if ~within_threshold(statistics.mard, contract.median_threshold) || ...
            ~within_threshold(statistics.p95, contract.p95_threshold) || ...
            any(~arrayfun(@(value) within_threshold(value, ...
            contract.median_threshold), groupDeviation))
        calibration.status = 'M04_SCALE_NOT_IDENTIFIED';
        return;
    end
    confirmation = selection.rows(strcmp({selection.rows.role}, 'confirmation'));
    calibration.status = 'M04_CALIBRATION_IDENTIFIED';
    calibration.samples_per_reference_length = selectedDensity;
    calibration.reference_length_mm = frozenLength;
    calibration.reference_length_text = sprintf('%.17g', frozenLength);
    calibration.scale_statistics = statistics;
    calibration.discovery_results = discoveryResults;
    calibration.confirmation_rows = compact_rows(confirmation);
end

function calibration = base_calibration(selection, candidates, results, absoluteTolerance)
    contract = legacy_calibration_contract();
    calibration = struct('schema_version', '1.0', ...
        'status', '', 'selection_sha256', selection.selection_sha256, ...
        'workbook_sha256', selection.workbook_sha256, ...
        'compiler_version', contract.compiler_version, ...
        'descriptor_definition_sha256', ...
        contract.descriptor_definition_sha256, ...
        'legacy_profile_sha256', contract.legacy_profile_sha256, ...
        'tpms_designer_commit', contract.tpms_designer_commit, ...
        'candidate_densities', candidates, 'density_results', results, ...
        'thresholds', struct('median', contract.median_threshold, ...
        'p95', contract.p95_threshold, ...
        'absolute_tolerance', double(absoluteTolerance)));
end

function rows = compact_rows(input)
    rows = repmat(struct('row_id','','selection_digest','','method','', ...
        'excel_row',0), numel(input), 1);
    for index = 1:numel(input)
        rows(index) = struct('row_id', input(index).row_id, ...
            'selection_digest', input(index).selection_digest, ...
            'method', input(index).method, 'excel_row', input(index).excel_row);
    end
end

function values = validate_values(result, errorId)
    names = {'relativeVolume','relativeArea','thickness','poreDiameter','areaMean'};
    if ~isstruct(result) || ~isscalar(result) || ~isfield(result, 'values') || ...
            ~isstruct(result.values) || ~all(isfield(result.values, names))
        throw(MException(errorId, 'calibration descriptor result is incomplete'));
    end
    values = result.values;
    for index = 1:numel(names)
        value = values.(names{index});
        if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ~isfinite(value)
            throw(MException(errorId, 'calibration descriptor result is nonfinite'));
        end
    end
end

function result = empty_density_result()
    result = struct('density',0,'relativeVolume_median',0, ...
        'relativeVolume_p95',0,'relativeArea_median',0, ...
        'relativeArea_p95',0,'pooled_median',0,'pooled_p95',0, ...
        'eligible',false);
end

function value = relative_error(computed, archived, absoluteTolerance)
    value = abs(computed - archived) ./ max(abs(archived), absoluteTolerance);
end

function value = deterministic_percentile(values, probability)
    values = sort(double(values(:)));
    position = 1 + (numel(values) - 1) * probability;
    lowerIndex = floor(position);
    upperIndex = ceil(position);
    fraction = position - lowerIndex;
    value = values(lowerIndex) * (1 - fraction) + values(upperIndex) * fraction;
end

function tf = within_threshold(value, threshold)
    tf = value <= threshold + 64 * eps(max(1, abs(threshold)));
end
