function text = canonical_legacy_calibration_freeze(freeze)
%CANONICAL_LEGACY_CALIBRATION_FREEZE Fixed-order freeze serialization.

    lines = { ...
        ['schema_version=', freeze.schema_version], ...
        ['status=', freeze.status], ...
        ['selection_sha256=', freeze.selection_sha256], ...
        ['workbook_sha256=', freeze.workbook_sha256], ...
        ['compiler_version=', freeze.compiler_version], ...
        ['descriptor_definition_sha256=', freeze.descriptor_definition_sha256], ...
        ['legacy_profile_sha256=', freeze.legacy_profile_sha256], ...
        ['tpms_designer_commit=', freeze.tpms_designer_commit], ...
        sprintf('samples_per_reference_length=%d', ...
        freeze.samples_per_reference_length), ...
        sprintf('reference_length_mm=%.17g', freeze.reference_length_mm), ...
        ['reference_length_text=', freeze.reference_length_text], ...
        sprintf('threshold_median=%.17g', freeze.thresholds.median), ...
        sprintf('threshold_p95=%.17g', freeze.thresholds.p95), ...
        sprintf('absolute_tolerance=%.17g', ...
        freeze.thresholds.absolute_tolerance)};
    for index = 1:numel(freeze.density_results)
        item = freeze.density_results(index);
        lines{end + 1} = sprintf([ ...
            'density=%d|rv_med=%.17g|rv_p95=%.17g|' ...
            'ra_med=%.17g|ra_p95=%.17g|pool_med=%.17g|' ...
            'pool_p95=%.17g|eligible=%d'], item.density, ...
            item.relativeVolume_median, item.relativeVolume_p95, ...
            item.relativeArea_median, item.relativeArea_p95, ...
            item.pooled_median, item.pooled_p95, item.eligible); %#ok<AGROW>
    end
    estimates = freeze.scale_statistics.estimates;
    for index = 1:numel(estimates)
        lines{end + 1} = sprintf('scale_estimate_%d=%.17g', ...
            index, estimates(index)); %#ok<AGROW>
    end
    lines{end + 1} = sprintf('scale_mard=%.17g', ...
        freeze.scale_statistics.mard);
    lines{end + 1} = sprintf('scale_p95=%.17g', ...
        freeze.scale_statistics.p95);
    lines{end + 1} = sprintf('scale_maximum=%.17g', ...
        freeze.scale_statistics.maximum);
    lines{end + 1} = sprintf('scale_group_medians=%.17g,%.17g,%.17g', ...
        freeze.scale_statistics.group_medians);
    lines{end + 1} = sprintf( ...
        'scale_group_relative_deviation=%.17g,%.17g,%.17g', ...
        freeze.scale_statistics.group_relative_deviation);
    for index = 1:numel(freeze.discovery_results)
        item = freeze.discovery_results(index);
        a = item.archived;
        c = item.computed_at_unit_length;
        lines{end + 1} = sprintf([ ...
            'discovery=%s|%s|%s|%d|' ...
            'a=%.17g,%.17g,%.17g,%.17g,%.17g|' ...
            'c=%.17g,%.17g,%.17g,%.17g,%.17g'], ...
            item.row_id, item.method, item.selection_digest, item.excel_row, ...
            a.relativeVolume, a.relativeArea, a.thickness, ...
            a.poreDiameter, a.areaMean, c.relativeVolume, ...
            c.relativeArea, c.thickness, c.poreDiameter, c.areaMean); %#ok<AGROW>
    end
    for index = 1:numel(freeze.confirmation_rows)
        item = freeze.confirmation_rows(index);
        lines{end + 1} = sprintf('confirmation=%s|%s|%s|%d', ...
            item.row_id, item.method, item.selection_digest, ...
            item.excel_row); %#ok<AGROW>
    end
    text = [strjoin(lines, newline), newline];
end
