function text = canonical_small_gate0_selection(workbookHash, rows, config)
%CANONICAL_SMALL_GATE0_SELECTION Bind all selected inputs in fixed order.

    lines = {['workbook_sha256=', char(workbookHash)], ...
        'selection_protocol=M04-v2-selection', ...
        ['compiler_version=', compiler_version()], ...
        ['parameter_domain_manifest_sha256=', ...
        config.parameter_domain_manifest_sha256], ...
        ['descriptor_definition_sha256=', ...
        config.descriptor_definition_sha256]};
    for index = 1:numel(rows)
        row = rows(index);
        parameters = row.raw_parameters;
        archived = row.archived_descriptors;
        lines{end + 1} = sprintf([ ...
            '%s|%s|%d|%s|%s|' ...
            'c0=%.17g|c1=%.17g|c2=%.17g|w=%.17g|' ...
            'relativeVolume=%.17g|relativeArea=%.17g|' ...
            'thickness=%.17g|poreDiameter=%.17g|areaMean=%.17g'], ...
            row.sheet, row.method, row.excel_row, row.role, ...
            row.selection_digest, parameters.c0, parameters.c1, ...
            parameters.c2, parameters.w, archived.relativeVolume, ...
            archived.relativeArea, archived.thickness, ...
            archived.poreDiameter, archived.areaMean); %#ok<AGROW>
    end
    text = [strjoin(lines, newline), newline];
end
