function freeze = freeze_legacy_calibration(calibration, selection, outputPath)
%FREEZE_LEGACY_CALIBRATION Atomically publish immutable discovery results.

    errorId = 'MATLABGyroid:M04Gate0NotFrozen';
    outputPath = validate_text_scalar(outputPath, 'freeze_path', errorId);
    if exist(outputPath, 'file') ~= 0 || exist(outputPath, 'dir') ~= 0
        throw(MException('MATLABGyroid:OutputConflict', ...
            'refusing to overwrite calibration freeze: %s', outputPath));
    end
    selection = verify_small_gate0_selection(selection);
    required = {'status','selection_sha256','candidate_densities', ...
        'samples_per_reference_length','reference_length_mm', ...
        'reference_length_text','scale_statistics','discovery_results', ...
        'confirmation_rows','density_results','thresholds'};
    if ~isstruct(calibration) || ~isscalar(calibration) || ...
            ~all(isfield(calibration, required))
        throw(MException(errorId, 'calibration freeze inputs are incomplete'));
    end
    status = validate_text_scalar(calibration.status, ...
        'calibration.status', errorId);
    selectionHash = validate_text_scalar(calibration.selection_sha256, ...
        'calibration.selection_sha256', errorId);
    if ~strcmp(status, 'M04_CALIBRATION_IDENTIFIED') || ...
            ~strcmp(selectionHash, selection.selection_sha256)
        throw(MException(errorId, 'calibration is not identified for this selection'));
    end
    assert_calibration_integrity(calibration, selection, errorId);
    freeze = struct('schema_version', '1.0', ...
        'status', 'M04_CALIBRATION_FROZEN', ...
        'selection_sha256', calibration.selection_sha256, ...
        'workbook_sha256', calibration.workbook_sha256, ...
        'compiler_version', calibration.compiler_version, ...
        'descriptor_definition_sha256', ...
        calibration.descriptor_definition_sha256, ...
        'legacy_profile_sha256', calibration.legacy_profile_sha256, ...
        'tpms_designer_commit', calibration.tpms_designer_commit, ...
        'samples_per_reference_length', ...
        calibration.samples_per_reference_length, ...
        'reference_length_mm', calibration.reference_length_mm, ...
        'reference_length_text', calibration.reference_length_text, ...
        'thresholds', calibration.thresholds, ...
        'density_results', calibration.density_results, ...
        'scale_statistics', calibration.scale_statistics, ...
        'discovery_results', calibration.discovery_results, ...
        'confirmation_rows', calibration.confirmation_rows, ...
        'freeze_sha256', '');
    freeze.freeze_sha256 = sha256_text( ...
        canonical_legacy_calibration_freeze(freeze));
    write_json_atomic(freeze, outputPath);
end

function assert_calibration_integrity(calibration, selection, errorId)
    validate_legacy_calibration_payload(calibration);
    contract = legacy_calibration_contract();
    if ~isnumeric(calibration.candidate_densities) || ...
            ~isequal(double(calibration.candidate_densities(:))', ...
            contract.candidate_densities) || ...
            ~strcmp(calibration.workbook_sha256, selection.workbook_sha256)
        throw(MException(errorId, 'calibration contract fields were overridden'));
    end
    discovery = selection.rows(strcmp({selection.rows.role}, 'discovery'));
    confirmation = selection.rows(strcmp({selection.rows.role}, 'confirmation'));
    if numel(calibration.discovery_results) ~= 6 || ...
            numel(calibration.confirmation_rows) ~= 30
        throw(MException(errorId, 'calibration case identities are incomplete'));
    end
    for index = 1:numel(discovery)
        item = calibration.discovery_results(index);
        if ~strcmp(item.row_id, discovery(index).row_id) || ...
                ~strcmp(item.selection_digest, discovery(index).selection_digest) || ...
                ~strcmp(item.method, discovery(index).method) || ...
                item.excel_row ~= discovery(index).excel_row || ...
                ~isequal(item.archived, discovery(index).archived_descriptors)
            throw(MException(errorId, 'calibration discovery identity was overridden'));
        end
    end
    for index = 1:numel(confirmation)
        item = calibration.confirmation_rows(index);
        if ~strcmp(item.row_id, confirmation(index).row_id) || ...
                ~strcmp(item.selection_digest, confirmation(index).selection_digest) || ...
                ~strcmp(item.method, confirmation(index).method) || ...
                item.excel_row ~= confirmation(index).excel_row
            throw(MException(errorId, 'calibration confirmation identity was overridden'));
        end
    end
end
