function validate_legacy_calibration_payload(payload)
%VALIDATE_LEGACY_CALIBRATION_PAYLOAD Re-derive every checkable M04 result.

    errorId = 'MATLABGyroid:M04Gate0NotFrozen';
    contract = legacy_calibration_contract();
    required = {'selection_sha256','workbook_sha256','compiler_version', ...
        'descriptor_definition_sha256','legacy_profile_sha256', ...
        'tpms_designer_commit','samples_per_reference_length', ...
        'reference_length_mm','reference_length_text','thresholds', ...
        'density_results','scale_statistics','discovery_results', ...
        'confirmation_rows'};
    if ~isstruct(payload) || ~isscalar(payload) || ...
            ~all(isfield(payload, required))
        reject(errorId, 'calibration result fields are incomplete');
    end
    require_text(payload.selection_sha256, contract.selection_sha256, errorId);
    require_text(payload.workbook_sha256, contract.workbook_sha256, errorId);
    require_text(payload.compiler_version, contract.compiler_version, errorId);
    require_text(payload.descriptor_definition_sha256, ...
        contract.descriptor_definition_sha256, errorId);
    require_text(payload.legacy_profile_sha256, ...
        contract.legacy_profile_sha256, errorId);
    require_text(payload.tpms_designer_commit, ...
        contract.tpms_designer_commit, errorId);
    validate_thresholds(payload.thresholds, contract, errorId);
    validate_density_results(payload, contract, errorId);
    validate_scale_results(payload, contract, errorId);
    validate_case_identities(payload, contract, errorId);
end

function validate_thresholds(thresholds, contract, errorId)
    required = {'median','p95','absolute_tolerance'};
    if ~isstruct(thresholds) || ~isscalar(thresholds) || ...
            ~all(isfield(thresholds, required)) || ...
            ~is_finite_scalar(thresholds.median) || ...
            ~is_finite_scalar(thresholds.p95) || ...
            ~is_finite_scalar(thresholds.absolute_tolerance) || ...
            thresholds.median ~= contract.median_threshold || ...
            thresholds.p95 ~= contract.p95_threshold || ...
            thresholds.absolute_tolerance ~= contract.absolute_tolerance
        reject(errorId, 'calibration tolerances were overridden');
    end
end

function validate_density_results(payload, contract, errorId)
    results = payload.density_results;
    fields = {'density','relativeVolume_median','relativeVolume_p95', ...
        'relativeArea_median','relativeArea_p95','pooled_median', ...
        'pooled_p95','eligible'};
    if ~isstruct(results) || numel(results) ~= ...
            numel(contract.candidate_densities) || ~all(isfield(results, fields)) || ...
            ~isequal(double([results.density]), contract.candidate_densities)
        reject(errorId, 'calibration density candidates were overridden');
    end
    metrics = fields(2:7);
    for index = 1:numel(results)
        for fieldIndex = 1:numel(metrics)
            value = results(index).(metrics{fieldIndex});
            if ~is_finite_scalar(value) || value < 0
                reject(errorId, 'calibration density statistics are invalid');
            end
        end
        eligible = results(index).eligible;
        if ~(islogical(eligible) || isnumeric(eligible)) || ...
                ~isscalar(eligible) || ~isfinite(double(eligible)) || ...
                ~ismember(double(eligible), [0, 1])
            reject(errorId, 'calibration density eligibility is invalid');
        end
        expected = within_threshold(results(index).relativeVolume_median, ...
            contract.median_threshold) && ...
            within_threshold(results(index).relativeVolume_p95, ...
            contract.p95_threshold) && ...
            within_threshold(results(index).relativeArea_median, ...
            contract.median_threshold) && ...
            within_threshold(results(index).relativeArea_p95, ...
            contract.p95_threshold);
        if logical(eligible) ~= expected
            reject(errorId, 'calibration density eligibility is inconsistent');
        end
    end
    eligibleIndices = find(logical([results.eligible]));
    if isempty(eligibleIndices)
        reject(errorId, 'calibration contains no eligible density');
    end
    ranking = [[results(eligibleIndices).pooled_median]', ...
        [results(eligibleIndices).pooled_p95]', ...
        [results(eligibleIndices).density]'];
    [~, order] = sortrows(ranking, [1, 2, 3]);
    expectedDensity = results(eligibleIndices(order(1))).density;
    if ~is_finite_scalar(payload.samples_per_reference_length) || ...
            payload.samples_per_reference_length ~= expectedDensity
        reject(errorId, 'calibration selected density is inconsistent');
    end
end

function validate_scale_results(payload, contract, errorId)
    statistics = payload.scale_statistics;
    fields = {'mard','p95','maximum','group_medians', ...
        'group_relative_deviation','estimates'};
    if ~isstruct(statistics) || ~isscalar(statistics) || ...
            ~all(isfield(statistics, fields)) || ...
            ~isnumeric(statistics.estimates) || ...
            ~isreal(statistics.estimates) || ...
            ~isequal(size(statistics.estimates), [6, 3]) || ...
            any(~isfinite(statistics.estimates(:))) || ...
            any(statistics.estimates(:) <= 0) || ...
            ~is_finite_scalar(payload.reference_length_mm) || ...
            payload.reference_length_mm <= 0
        reject(errorId, 'calibration scale estimates are invalid');
    end
    estimates = double(statistics.estimates);
    expectedLength = median(estimates, 'all');
    tolerance = numeric_tolerance([estimates(:); expectedLength]);
    if abs(double(payload.reference_length_mm) - expectedLength) > tolerance || ...
            ~strcmp(validate_text_scalar(payload.reference_length_text, ...
            'reference_length_text', errorId), sprintf('%.17g', expectedLength))
        reject(errorId, 'calibration reference length is inconsistent');
    end
    deviation = abs(estimates - expectedLength) ./ expectedLength;
    expectedMard = median(deviation, 'all');
    expectedP95 = deterministic_percentile(deviation(:)', .95);
    expectedMaximum = max(deviation, [], 'all');
    expectedGroupMedians = median(estimates, 1);
    expectedGroupDeviation = ...
        abs(expectedGroupMedians - expectedLength) ./ expectedLength;
    require_close(statistics.mard, expectedMard, tolerance, errorId);
    require_close(statistics.p95, expectedP95, tolerance, errorId);
    require_close(statistics.maximum, expectedMaximum, tolerance, errorId);
    require_array_close(statistics.group_medians, ...
        expectedGroupMedians, tolerance, errorId);
    require_array_close(statistics.group_relative_deviation, ...
        expectedGroupDeviation, tolerance, errorId);
    if ~within_threshold(expectedMard, contract.median_threshold) || ...
            ~within_threshold(expectedP95, contract.p95_threshold) || ...
            any(~arrayfun(@(value) within_threshold(value, ...
            contract.median_threshold), expectedGroupDeviation))
        reject(errorId, 'calibration scale thresholds are not satisfied');
    end
end

function validate_case_identities(payload, contract, errorId)
    discovery = payload.discovery_results;
    confirmation = payload.confirmation_rows;
    if ~isstruct(discovery) || numel(discovery) ~= 6 || ...
            ~isstruct(confirmation) || numel(confirmation) ~= 30 || ...
            ~strcmp(legacy_case_identity_sha256(discovery), ...
            contract.discovery_identity_sha256) || ...
            ~strcmp(legacy_case_identity_sha256(confirmation), ...
            contract.confirmation_identity_sha256)
        reject(errorId, 'calibration case identities were overridden');
    end
    names = {'relativeVolume','relativeArea','thickness', ...
        'poreDiameter','areaMean'};
    recomputedEstimates = zeros(6, 3);
    volumeErrors = zeros(1, 6);
    areaErrors = zeros(1, 6);
    for index = 1:6
        if ~isfield(discovery(index), 'archived') || ...
                ~isfield(discovery(index), 'computed_at_unit_length')
            reject(errorId, 'calibration discovery values are incomplete');
        end
        archived = discovery(index).archived;
        computed = discovery(index).computed_at_unit_length;
        if ~isstruct(archived) || ~isstruct(computed) || ...
                ~all(isfield(archived, names)) || ~all(isfield(computed, names))
            reject(errorId, 'calibration discovery values are incomplete');
        end
        for nameIndex = 1:numel(names)
            if ~is_finite_scalar(archived.(names{nameIndex})) || ...
                    ~is_finite_scalar(computed.(names{nameIndex}))
                reject(errorId, 'calibration discovery values are nonfinite');
            end
        end
        if computed.thickness <= 0 || computed.poreDiameter <= 0 || ...
                computed.areaMean <= 0 || archived.thickness <= 0 || ...
                archived.poreDiameter <= 0 || archived.areaMean <= 0
            reject(errorId, 'calibration discovery scales are nonpositive');
        end
        recomputedEstimates(index, :) = [ ...
            archived.thickness / computed.thickness, ...
            archived.poreDiameter / computed.poreDiameter, ...
            sqrt(archived.areaMean / computed.areaMean)];
        volumeErrors(index) = relative_error(computed.relativeVolume, ...
            archived.relativeVolume, contract.absolute_tolerance);
        areaErrors(index) = relative_error(computed.relativeArea, ...
            archived.relativeArea, contract.absolute_tolerance);
    end
    tolerance = numeric_tolerance(recomputedEstimates(:));
    require_array_close(payload.scale_statistics.estimates, ...
        recomputedEstimates, tolerance, errorId);
    results = payload.density_results;
    selectedIndex = find([results.density] == ...
        payload.samples_per_reference_length, 1);
    pooled = [volumeErrors, areaErrors];
    selectedExpected = [median(volumeErrors), ...
        deterministic_percentile(volumeErrors, .95), median(areaErrors), ...
        deterministic_percentile(areaErrors, .95), median(pooled), ...
        deterministic_percentile(pooled, .95)];
    selectedActual = [results(selectedIndex).relativeVolume_median, ...
        results(selectedIndex).relativeVolume_p95, ...
        results(selectedIndex).relativeArea_median, ...
        results(selectedIndex).relativeArea_p95, ...
        results(selectedIndex).pooled_median, results(selectedIndex).pooled_p95];
    require_array_close(selectedActual, selectedExpected, ...
        numeric_tolerance(selectedExpected), errorId);
end

function value = relative_error(computed, archived, absoluteTolerance)
    value = abs(computed - archived) ./ max(abs(archived), absoluteTolerance);
end

function value = deterministic_percentile(values, probability)
    values = sort(double(values(:)));
    position = 1 + (numel(values) - 1) * probability;
    lowerIndex = floor(position);
    upperIndex = ceil(position);
    fraction = position - lowerIndex;
    value = values(lowerIndex) * (1 - fraction) + values(upperIndex) * fraction;
end

function tf = within_threshold(value, threshold)
    tf = value <= threshold + 64 * eps(max(1, abs(threshold)));
end

function tf = is_finite_scalar(value)
    tf = isnumeric(value) && isscalar(value) && isreal(value) && isfinite(value);
end

function tolerance = numeric_tolerance(values)
    tolerance = 128 * eps(max(1, max(abs(double(values(:))))));
end

function require_close(actual, expected, tolerance, errorId)
    if ~is_finite_scalar(actual) || abs(double(actual) - expected) > tolerance
        reject(errorId, 'calibration derived statistics are inconsistent');
    end
end

function require_array_close(actual, expected, tolerance, errorId)
    shapeMatches = isequal(size(actual), size(expected)) || ...
        (isvector(actual) && isvector(expected) && numel(actual) == numel(expected));
    if ~isnumeric(actual) || ~isreal(actual) || ...
            ~shapeMatches || ...
            any(~isfinite(actual(:))) || ...
            any(abs(double(actual(:)) - double(expected(:))) > tolerance)
        reject(errorId, 'calibration derived arrays are inconsistent');
    end
end

function require_text(actual, expected, errorId)
    actual = validate_text_scalar(actual, 'calibration contract value', errorId);
    if ~strcmp(actual, expected)
        reject(errorId, 'calibration contract fields were overridden');
    end
end

function reject(errorId, message)
    throw(MException(errorId, message));
end
